<<<<<<< HEAD
=======
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
>>>>>>> 441d1ad2e6f7aa065c38bf9ca9c46dfad7683d47
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ClientLayout from "@/components/ClientLayout";
<<<<<<< HEAD
import { Toaster } from "sonner";
import { BackgroundBeamsWithCollision } from "@/components/ui/backgroundbeams";
=======
>>>>>>> 441d1ad2e6f7aa065c38bf9ca9c46dfad7683d47

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Sonic Seeker",
=======
  title: "Create Next App",
>>>>>>> 441d1ad2e6f7aa065c38bf9ca9c46dfad7683d47
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-background text-foreground`}
      >
        <ClientLayout>
          <Toaster position="top-center" theme="dark" />
          <Header />
          <BackgroundBeamsWithCollision className="flex-grow z-0 bg-background">
            <main className="relative z-10 w-full">{children}</main>
          </BackgroundBeamsWithCollision>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ClientLayout>
          <Header />
          <main className="flex-grow">{children}</main>
>>>>>>> 441d1ad2e6f7aa065c38bf9ca9c46dfad7683d47
          <Footer />
        </ClientLayout>
      </body>
    </html>
  );
}
