import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ClientLayout from "@/components/ClientLayout";
import { Toaster } from "sonner";
import { BackgroundBeamsWithCollision } from "@/components/ui/backgroundbeams";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-background text-foreground`}
      >
        <ClientLayout>
          <Toaster position="top-center" theme="dark" />
          <Header />
          <BackgroundBeamsWithCollision className="flex-grow z-0 bg-background">
            <main className="relative z-10 w-full">{children}</main>
          </BackgroundBeamsWithCollision>
          <Footer />
        </ClientLayout>
      </body>
    </html>
  );
}
